#!/bin/sh

printf 'HELLO FROM TAILSITTER. '
if [ -n "$*" ]; then
	printf 'ARGS:'
	printf ' <%s>' "$@"
else
	printf 'NO ARGS'
fi

printf '(TAILSITTER_SECRET_PASSWORD is <%s>)' "$TAILSITTER_SECRET_PASSWORD"

printf '\n\n'