#!/bin/sh

printf 'HELLO FROM TAILSITTER. '
if [ -n "$*" ]; then
	printf 'ARGS:'
	printf ' <%s>' "$@"
else
	printf 'NO ARGS'
fi

printf '(TAILSITTER_RUN_ENV is <%s>)' "$TAILSITTER_RUN_ENV"

printf '\n\n'